const data = [
  {
    id: '1',
    status: 'lead',
    address: '123 Main St.',
    prediction: '90%',
  },
  {
    id: '2',
    status: 'copper',
    address: '456 5th ave',
    prediction: '65%',
  },
  {
    id: '3',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '4',
    status: 'copper',
    address: '456 5th ave.',
    prediction: '45%',
  },
  {
    id: '5',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '6',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '7',
    status: 'copper',
    address: '456 5th ave.',
    prediction: '45%',
  },
  {
    id: '8',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '9',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '10',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '11',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '12',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '13',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  ////////////////////////////////////

  {
    id: '6',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '7',
    status: 'copper',
    address: '456 5th ave.',
    prediction: '45%',
  },
  {
    id: '8',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '9',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '10',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '11',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '12',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '13',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '6',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '7',
    status: 'copper',
    address: '456 5th ave.',
    prediction: '45%',
  },
  {
    id: '8',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '9',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '10',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '11',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '12',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '13',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '6',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '7',
    status: 'copper',
    address: '456 5th ave.',
    prediction: '45%',
  },
  {
    id: '8',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '9',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '10',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '11',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '12',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '13',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '6',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '7',
    status: 'copper',
    address: '456 5th ave.',
    prediction: '45%',
  },
  {
    id: '8',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '9',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '10',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '11',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '12',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '13',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '6',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '7',
    status: 'copper',
    address: '456 5th ave.',
    prediction: '45%',
  },
  {
    id: '8',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '9',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '10',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
  {
    id: '11',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '12',
    status: 'lead',
    address: '123 Main St.',
    prediction: '98%',
  },
  {
    id: '13',
    status: 'iron',
    address: '667 Central Blvd.',
    prediction: '87%',
  },
]

export default data;
