name: PR Checks

on:
  pull_request:

jobs:
  checks:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Install pnpm
      run: npm i pnpm@latest -g

    - name: Workspace install
      run: pnpm install

    - name: Build
      run: pnpm build
