name: Release packages

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  version-and-release:
    runs-on: macos-latest

    steps:
    - name: Checkout code repo
      uses: actions/checkout@v2
    
    ## Removing the publish automation for now
    ## There is a good flow in place with pnpm+changesets, but it does involve
    ## committing changes in between CLI commands. We should get more comfortable
    ## with the process before we attempt to completely automate it. 
