name: Release packages

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Workspace install
      run: npm ci
    
    - name: Workspace build
      run: npm run build

    - name: Publish packages under the `next` dist tag
      run: npx lerna publish from-package --dist-tag next --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
